version: 2
updates:
  
  - package-ecosystem: "nuget"
    directory: "/FraudDetection/src/DurableFunctions.UseCases.FraudDetection"
    schedule:
      interval: "daily"
      time: "19:00"
    open-pull-requests-limit: 10
    reviewers:
      - "marcduiker"

  - package-ecosystem: "nuget"
    directory: "/NotifySupport/src/DurableFunctions.UseCases.NotifySupport"
    schedule:
      interval: "daily"
      time: "19:01"
    open-pull-requests-limit: 10
    reviewers:
      - "marcduiker"