# @name notifyRequest
POST http://localhost:7071/api/NotifySupportHttpClient
Content-Type: application/json

{
    "phoneNumbers": [
        "123",
        "456",
        "789"],
    "message" : "HALP!",
    "waitTimeForEscalation" : 90,
    "maxNotificationAttempts" : 3
}

### Send CallBack event
# Update the instanceId with the instanceId from the SendNotificationActivity log.
@instanceId=d61187557a7d41fe99c7bd22eb96d28e:0 
@eventName=CallBack
@taskHub=DFUseCasesv1
POST http://localhost:7071/runtime/webhooks/durabletask/instances/{{instanceId}}/raiseEvent/{{eventName}}
    ?taskHub={{taskHub}}
    &connection=Storage
    &code=U0gR6nOWK0ovQKFHWUdQeyAi3jpFmTQPyngadzs1J5KW5oyUQWlnqQ==
Content-Type: application/json

true

