name: CodeTour Watch And Link Checker

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    codetour-and-linkchecker:
        runs-on: ubuntu-latest
        steps:
            - name: 'Watch CodeTour changes'
              uses: pozil/codetour-watch@v1.3.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v1.0.8
              with:
                args:  --verbose --no-progress --exclude-mail --exclude-loopback --exclude "https?://localhost.*" -- "**/*.md"
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
            - name: Fail if there were link errors
              run: exit ${{ steps.lychee.outputs.exit_code }}
            - name: 'Checkout source code'
              uses: actions/checkout@v2

